---

- name: Gather instance facts
  shell: "curl -s http://169.254.169.254/latest/meta-data/instance-id | sed -e 's/^i-//'"
  register: instance_output

- name: Set network and instance facts
  set_fact:
    instance_name: "{{ instance_output.stdout }}"
    long_instance_name: "i-{{ instance_output.stdout }}"

- block:
    - name: Set hostname fact
      set_fact:
        hostname: "{{ instance_name }}"
  when: not ansible_env.HMPPS_ROLE|default(False)

- block:
    - name: Set hostname fact
      set_fact:
        hostname: "{{ ansible_env.HMPPS_ROLE }}-{{ instance_name }}"
  when: ansible_env.HMPPS_ROLE|default(False)

- name: Reload systemd daemon
  systemd:
    name: awslogs
    daemon_reload: true

- name: Stop our services to reconfigure them
  service:
    name: "{{ item }}"
    state: stopped
  with_items:
    - logstash
    - filebeat
    - awslogs
  become: true

- name: Set our grok pattern directory
  set_fact:
    grok_dir: /opt/logstash/patterns

- name: Ensure our grok filter directory exists
  file:
    path: "{{ grok_dir }}"
    state: directory
  become: true

- name: Add our grok filters
  copy:
    src: "{{ role_path }}/files/logstash/grok/{{ item }}"
    dest: "{{ grok_dir }}/{{ item }}"
  with_items:
    - nginx
    - tomcat
  become: true

- name: Update our logstash pipeline files
  template:
    src: "{{ role_path }}/templates/logstash/{{ item }}.j2"
    dest: "/etc/logstash/conf.d/{{ item }}"
  with_items:
    - "01-logstash-filebeat-input.conf"
    - "10-alfresco_audit.conf"
    - "20_catalina.conf"
    - "50_logstash-output.conf"
  become: true

- name: Create our filebeat config
  template:
    src: "{{ role_path }}/templates/filebeat.yml"
    dest: "/etc/filebeat/filebeat.yml"
  become: true

- name: Comment out our rsyslog forwarding rule
  template:
    src: "{{ role_path }}/templates/rsyslog/rsyslog.conf.j2"
    dest: "/etc/rsyslog.conf"
  become: true
  notify:
    - restart rsyslog

- name: Replace our awslogs conf file
  template:
    src: "{{ role_path }}/templates/awslogs.conf.j2"
    dest: "/var/awslogs/etc/awslogs.conf"

- name: Start our services post reconfiguration
  service:
    name: "{{ item }}"
    state: started
  with_items:
    - logstash
    - filebeat
    - awslogs
  become: true
