---

- name: ensure that we have nfs utils installed
  yum:
    name: nfs-utils
    state: present
  become: true

- name: Ensure directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0775
    owner: tomcat
    group: tomcat
  with_items:
    - /srv/alf_data/contentstore
    - /srv/alf_data/contentstore.deleted

- name: Get current AZ from AWS.
  uri:
    url: http://169.254.169.254/latest/meta-data/placement/availability-zone
    return_content: yes
  register: aws_current_az

- name: Ensure ContentStore EFS volume is mounted.
  mount:
    name: /srv/alf_data/contentstore
    src: "{{ aws_current_az.content }}.{{ content_store_id }}.efs.{{ region }}.amazonaws.com:/"
    fstype: nfs4
    opts: nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport
    state: mounted

- name: Ensure ContentStore.Deleted EFS volume is mounted.
  mount:
    name: /srv/alf_data/contentstore.deleted
    src: "{{ aws_current_az.content }}.{{ content_store_deleted_id }}.efs.{{ region }}.amazonaws.com:/"
    fstype: nfs4
    opts: nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport
    state: mounted
