---

- name: Gather instance facts
  ec2_facts:
  register: instance_facts

- name: Reconfigure our logging services so we audit correctly
  include: configure_auditing.yml

- name: Ensure we have our alfresco logging directory in place
  file:
    path: /usr/share/tomcat/shared/classes/extension
    state: directory
    owner: tomcat
    group: tomcat
    mode: 775
  become: true

- name: Ensure we have our logging properties installed
  copy:
    src: "{{ role_path }}/files/log4j.properties"
    dest: /usr/share/tomcat/shared/classes/extension/log4j.properties
    owner: tomcat
    group: tomcat
  become: true

- name: Get our ghostscript version
  command: "ghostscript --version"
  register: gs_version
  no_log: true

- name: Find our soffice.bin file
  find:
    paths: /
    recurse: yes
    patterns: "soffice.bin"
    file_type: "file"
  register: soffice_result
  failed_when: soffice_result.matched == 0

- name: Set template facts
  set_fact:
    libre_office_path: "{{ soffice_result.files[0].path }}"
    ghostscript_ver: "{{ gs_version.stdout }}"
    alf_properties: /usr/share/tomcat/shared/classes/alfresco-global.properties
    csrf_properties: /usr/share/tomcat/shared/classes/alfresco/web-extension/share-config-custom.xml
    admin_properties: /usr/share/tomcat/shared/classes/alfresco/extension/web-scripts-config-custom.xml
    interface_ip: "{{ instance_facts.ansible_facts.ansible_ec2_local_ipv4 }}"
    slingshot_properties: /usr/share/tomcat/shared/classes/alfresco/web-extension/custom-slingshot-application-context.xml

- name: Create our templated config files
  template:
    src: "{{ role_path }}/templates/{{ item.file }}"
    dest: "{{ item.dest }}"
  with_items:
    - { file: "alfresco-global.properties", dest: "{{ alf_properties }}" }
    - { file: "custom-slingshot-application-context.xml", dest: "{{ slingshot_properties }}" }
    - { file: "share-config-custom.xml", dest: "{{ csrf_properties }}" }
    - { file: "web-scripts-config-custom.xml", dest: "{{ admin_properties }}" }
    - { file: "context.xml", dest: "/usr/share/tomcat/conf/context.xml" }

- name: Download our shared session jar files, this will move to the packer builder
  get_url:
    url: "{{ item }}"
    dest: "/usr/share/tomcat/lib/{{ item|basename }}"
    owner: tomcat
    group: tomcat
  with_items:
    - https://repo1.maven.org/maven2/de/javakaffee/msm/memcached-session-manager/2.3.2/memcached-session-manager-2.3.2.jar
    - https://repo1.maven.org/maven2/de/javakaffee/msm/memcached-session-manager-tc7/2.3.2/memcached-session-manager-tc7-2.3.2.jar
    - https://repo1.maven.org/maven2/net/spy/spymemcached/2.12.3/spymemcached-2.12.3.jar

- name: Ensure our mounts have the correct permissions
  file:
    owner: tomcat
    group: tomcat
    dest: /srv/cache
    recurse: true

- name: Ensure we have our correct repo dirs on the mount
  file:
    state: directory
    path:  "{{ item }}"
    owner: tomcat
    group: tomcat
  with_items:
    - /srv/alf_data/contentstore
    - /srv/alf_data/contentstore.deleted

# To be removed as we are using base tomcat, currently we still have the service in play on integration, it is removed in
# alf ami's going forward but we'll cause issues if we remove it from here for now
- name: Install our custom service
  service:
    name: tomcat-alfresco
    state: stopped
    enabled: true
  ignore_errors: true

- name: Start alfresco
  service:
    name: tomcat-alfresco
    state: started
  ignore_errors: true
