---

- name: Gather instance facts
  ec2_facts:
  register: instance_facts

- name: Get our ghostscript version
  command: "ghostscript --version"
  register: gs_version
  no_log: true

- name: Find our soffice.bin file
  find:
    paths: /
    recurse: yes
    patterns: "soffice.bin"
    file_type: "file"
  register: soffice_result
  failed_when: soffice_result.matched == 0

- name: Set template facts
  set_fact:
    libre_office_path: "{{ soffice_result.files[0].path }}"
    ghostscript_ver: "{{ gs_version.stdout }}"
    alf_properties: /usr/share/tomcat/shared/classes/alfresco-global.properties
    csrf_properties: /usr/share/tomcat/shared/classes/alfresco/web-extension/share-config-custom.xml
    interface_ip: "{{ instance_facts.ansible_facts.ansible_ec2_local_ipv4 }}"
    slingshot_properties: /usr/share/tomcat/shared/classes/alfresco/web-extension/custom-slingshot-application-context.xml

- name: Create our templated config files
  template:
    src: "{{ role_path }}/templates/{{ item.file }}"
    dest: "{{ item.dest }}"
  with_items:
    - { file: "alfresco-global.properties", dest: "{{ alf_properties }}" }
    - { file: "custom-slingshot-application-context.xml", dest: "{{ slingshot_properties }}" }
    - { file: "share-config-custom.xml", dest: "{{ csrf_properties }}" }

- name: Ensure our mounts have the correct permissions
  file:
    owner: tomcat
    group: tomcat
    dest: /srv/cache
    recurse: true

- name: Start alfresco
  service:
    name: tomcat-alfresco
    state: started
