---

- name: Gather instance facts
  ec2_facts:
  register: instance_facts
  
- name: Set facts
  set_fact:
    alf_properties: /usr/share/tomcat/shared/classes/alfresco-global.properties
    sl_properties: /usr/share/tomcat/shared/classes/alfresco/web-extension/custom-slingshot-application-context.xml

- name: Substitute our config vars
  command: "sed -i 's/##{{ item.key}}##/{{ item.value }}/g' {{ item.path }}"
  with_items:
    - { key: 'CONTENT_BUCKET_NAME', value: "{{bucket_name|default('')}}", path: "{{ alf_properties }}" }
    - { key: "ENCRYPTION_TYPE", value: "{{bucket_encrypt_type|default('')}}", path: "{{ alf_properties }}" }
    - { key: "KMS_KEY_ID", value: "{{bucket_key_id|default('')}}", path: "{{ alf_properties }}" }
    - { key: "ALF_DB_USER", value: "{{db_user|default('')}}", path: "{{ alf_properties }}" }
    - { key: "ALF_DB_PASSWORD", value: "{{db_password|default('')}}", path: "{{ alf_properties }}" }
    - { key: "ALF_DB_NAME", value: "{{db_name|default('')}}", path: "{{ alf_properties }}" }
    - { key: "ALF_HOSTNAME", value: "{{db_host|default('')}}", path: "{{ alf_properties }}" }
    - { key: "ALF_SERVERMODE", value: "{{server_mode|default('TEST')}}", path: "{{ alf_properties }}" }
    - { key: "ALF_CLUSTER_NAME", value: "{{cluster_name|default('')}}", path: "{{ alf_properties }}" }
    - { key: "ALF_CLUSTER_SUBNET", value: "{{cluster_subnet|default('')}}", path: "{{ alf_properties }}" }
    - { key: "MONITORING_SERVER", value: "{{monitoring_server_url|default('')}}", path: "{{ alf_properties }}" }
    - { key: "ES_CLUSTER_NAME", value: "{{monitoring_cluster_name|default('')}}", path: "{{ alf_properties }}" }
    - { key: "INTERFACE_IP", value: "{{instance_facts.ansible_facts.ansible_ec2_local_ipv4|default('0.0.0.0')}}" , path: "{{ sl_properties }}" }

- name: Start tomcat
  service:
    name: tomcat
    state: started
