---

- name: restart chronyd
  service:
    name: chronyd
    state: restarted

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted

- name: restart awslogs
  service:
    name: awslogs
    state: restarted
